algoritmo "Aluno"
// Função :
// Autor :
// Data : 29/03/2022
// Seção de Declarações 
var
n1,n2,n3,n4, media:real

inicio
//entrada

escreval("Digite a nota do primeiro bimestre: ")
leia(n1)
escreval("Digite a nota do segundo bimestre: ")
leia(n2)
escreval("Digite a nota do terceiro bimestre: ")
leia(n3)
escreval("Digite a nota do quarto bimestre: ")
leia(n4)

//processamento

media <- (n1+n2+n3+n4)/4


escreval("Sua media é: ,media")



fimalgoritmo
