algoritmo "AumentoSalario"
// Função : aumento de 30 para a professora
// Autor :
// Data : 29/03/2022
// Seção de Declarações 
var
salario,aumento,per,salario_final:real

inicio
//entrada

escreval("Solicite o salario: ")
leia(salario)
escreval("Solicite a porcentagem de aumento: ")
leia(per)



//processamento
aumento <- (salario*per/100)+salario

escreval("com o aumento vc vai receber:RS"  ,aumento)



//saida



fimalgoritmo
