algoritmo "Restaurante"
// Função : peso por comida
// Autor :
// Data : 29/03/2022
// Seção de Declarações 
var
quilo,peso,cliente,valor:real

inicio
//entrada
escreval("Escreva o valor cobrado por cada quilo: ")
leia(valor)
escreval("Escreva quantos quilos deu seu prato: ")
leia(quilo)

//processamento
valor <- (quilo+valor)

//saida

escreval("O total do seu prato deu: ,valor")
fimalgoritmo
